[2024-02-12T22:54:48.175+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi-load_to_pg.download_data manual__2024-02-12T22:54:46.862244+00:00 [queued]>
[2024-02-12T22:54:48.190+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi-load_to_pg.download_data manual__2024-02-12T22:54:46.862244+00:00 [queued]>
[2024-02-12T22:54:48.191+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-12T22:54:48.210+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_data> on 2024-02-12 22:54:46.862244+00:00
[2024-02-12T22:54:48.216+0000] {standard_task_runner.py:60} INFO - Started process 587 to run task
[2024-02-12T22:54:48.219+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi-load_to_pg', 'download_data', 'manual__2024-02-12T22:54:46.862244+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/dag_ny_taxi_load_to_pg.py', '--cfg-path', '/tmp/tmpfpkd1b7l']
[2024-02-12T22:54:48.220+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask download_data
[2024-02-12T22:54:48.273+0000] {task_command.py:423} INFO - Running <TaskInstance: ny_taxi-load_to_pg.download_data manual__2024-02-12T22:54:46.862244+00:00 [running]> on host 7b7b8b9b0fa9
[2024-02-12T22:54:48.355+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ny_taxi-load_to_pg' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T22:54:46.862244+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-12T22:54:46.862244+00:00'
[2024-02-12T22:56:44.425+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-02-12T22:56:44.427+0000] {process_utils.py:131} INFO - Sending 15 to group 587. PIDs of all processes in the group: [587]
[2024-02-12T22:56:44.428+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 587
[2024-02-12T22:56:44.429+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-12T22:56:44.481+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=587, status='terminated', exitcode=0, started='22:54:47') (587) terminated with exit code 0
