[2024-02-12T22:53:19.979+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ny_taxi-load_to_pg.download_data manual__2024-02-12T22:53:19.040386+00:00 [queued]>
[2024-02-12T22:53:19.989+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ny_taxi-load_to_pg.download_data manual__2024-02-12T22:53:19.040386+00:00 [queued]>
[2024-02-12T22:53:19.990+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-02-12T22:53:20.003+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_data> on 2024-02-12 22:53:19.040386+00:00
[2024-02-12T22:53:20.008+0000] {standard_task_runner.py:60} INFO - Started process 558 to run task
[2024-02-12T22:53:20.009+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'ny_taxi-load_to_pg', 'download_data', 'manual__2024-02-12T22:53:19.040386+00:00', '--job-id', '23', '--raw', '--subdir', 'DAGS_FOLDER/dag_ny_taxi_load_to_pg.py', '--cfg-path', '/tmp/tmp8ybrl_lf']
[2024-02-12T22:53:20.011+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask download_data
[2024-02-12T22:53:20.057+0000] {task_command.py:423} INFO - Running <TaskInstance: ny_taxi-load_to_pg.download_data manual__2024-02-12T22:53:19.040386+00:00 [running]> on host 7b7b8b9b0fa9
[2024-02-12T22:53:20.131+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='ny_taxi-load_to_pg' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2024-02-12T22:53:19.040386+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-12T22:53:19.040386+00:00'
[2024-02-12T22:56:47.153+0000] {local_task_job_runner.py:302} WARNING - State of this instance has been externally set to removed. Terminating instance.
[2024-02-12T22:56:47.157+0000] {process_utils.py:131} INFO - Sending 15 to group 558. PIDs of all processes in the group: [558]
[2024-02-12T22:56:47.158+0000] {process_utils.py:86} INFO - Sending the signal 15 to group 558
[2024-02-12T22:56:47.160+0000] {taskinstance.py:2450} ERROR - Received SIGTERM. Terminating subprocesses.
[2024-02-12T22:56:47.253+0000] {process_utils.py:79} INFO - Process psutil.Process(pid=558, status='terminated', exitcode=0, started='22:53:19') (558) terminated with exit code 0
